import java.io.File

fun main() {
    val papka=File("C:\\Papka")
    papka.mkdirs()
    val papka2=File(papka,"papka2")
        papka2.mkdirs()
    val papka3=File(papka,"papka3")
        papka3.mkdirs()

    val papka4=File(papka2,"pap4")
        papka4.mkdirs()
    val papka5=File(papka2,"pap5")
        papka5.mkdirs()
    val papka6=File(papka2,"pap6")
        papka6.mkdirs()
    val papka7=File(papka2,"pap7")
        papka7.mkdirs()

    val papka8=File(papka3,"pap8")
        papka8.mkdirs()
    val papka9=File(papka3,"pap9")
        papka9.mkdirs()
    val papka10=File(papka3,"pap10")
        papka10.mkdirs()
    val papka11=File(papka3,"pap11")
        papka11.mkdirs()

        val files2=File(papka2,"salom")
        files2.createNewFile()
        files2.writeText("Abror Azimjonov")
        val files3=File(papka3,"salom")
        files3.createNewFile()
        files3.writeText("Abror Azimjonov")
        val files4=File(papka4,"salom")
        files4.createNewFile()
        files4.writeText("Abror Azimjonov")
        val files5=File(papka5,"salom")
        files5.createNewFile()
        files5.writeText("Abror Azimjonov")


        val files6=File(papka6,"salom")
        files6.createNewFile()
        files6.writeText("Abror Azimjonov")
        val files7=File(papka7,"salom")
        files7.createNewFile()
        files7.writeText("Abror Azimjonov")
        val files8=File(papka8,"salom")
        files8.createNewFile()
        files8.writeText("Abror Azimjonov")
        val files9=File(papka9,"salom")
        files9.createNewFile()
        files9.writeText("Abror Azimjonov")
        val files10=File(papka10,"salom")
        files10.createNewFile()
        files10.writeText("Abror Azimjonov")
        val files11=File(papka11,"salom")
        files11.createNewFile()
        files11.writeText("Abror Azimjonov")
}